version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment: 
      - MONGODB_ADMIN_USER=
      - MONGODB_ADMIN_PASS=
    volumes:
      - './data/db:/data/db'
    ports:
     - '27017:27017'
  

  